/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useContext, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import AppContext from '../../context/AppContext'

export default React.forwardRef(function Model(props, ref) {
  const group = useRef()
  const groundRef = useRef()
  const { setMesh } = useContext(AppContext)
  const { nodes, materials, animations } = useGLTF('/model/village001.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    setMesh({ group, groundRef })
    if (actions.Animation) {
      actions.Animation.play()
    }
  }, [actions, setMesh])


  React.useImperativeHandle(ref, () => ({
    group: group.current,
    actions
  }))

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Drone01"
          castShadow
          //receiveShadow
          geometry={nodes.Drone01.geometry}
          material={materials.purple}
          position={[0.065, 0.037, -0.218]}
          rotation={[0, -0.912, -0.277]}
          scale={0.78}>
          <mesh
            name="Drone5_1"
            castShadow
            //receiveShadow
            geometry={nodes.Drone5_1.geometry}
            material={nodes.Drone5_1.material}
          />
          <mesh
            name="Wings_01"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_01.geometry}
            material={materials.gery}
            position={[-0.005, 0, 0.005]}
          />
          <mesh
            name="Wings_02"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_02.geometry}
            material={materials.gery}
            position={[0.004, 0, 0.005]}
          />
          <mesh
            name="Wings_03"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_03.geometry}
            material={materials.gery}
            position={[0.005, 0, -0.004]}
          />
        </mesh>
        <group
          name="Helicopter"
          position={[-0.002, 0.03, -0.187]}
          rotation={[-3.078, 1.075, -3.054]}>
          <mesh
            name="Mesh_9"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_9.geometry}
            material={materials.white}
          />
          <mesh
            name="Mesh_9_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_9_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Blades_02"
            castShadow
            //receiveShadow
            geometry={nodes.Blades_02.geometry}
            material={nodes.Blades_02.material}
            position={[-0.001, 0.003, 0]}
          />
        </group>
        <mesh
          name="Drone"
          castShadow
          //receiveShadow
          geometry={nodes.Drone.geometry}
          material={materials.purple}
          position={[-0.237, 0.037, -0.06]}
          scale={0.78}>
          <mesh
            name="Drone5_1002"
            castShadow
            //receiveShadow
            geometry={nodes.Drone5_1002.geometry}
            material={nodes.Drone5_1002.material}
          />
          <mesh
            name="Wings_01001"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_01001.geometry}
            material={materials.gery}
            position={[-0.005, 0, 0.005]}
            rotation={[0, -0.598, 0]}
          />
          <mesh
            name="Wings_01002"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_01002.geometry}
            material={materials.gery}
            position={[0.004, 0, 0.005]}
            rotation={[0, -0.598, 0]}
          />
          <mesh
            name="Wings_01003"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_01003.geometry}
            material={materials.gery}
            position={[0.004, 0, -0.004]}
            rotation={[0, -0.598, 0]}
          />
        </mesh>
        <group name="kran" position={[-0.231, 0, -0.111]}>
          <mesh
            name="Mesh_33"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_33.geometry}
            material={materials.gery}
          />
          <mesh
            name="Mesh_33_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_33_1.geometry}
            material={materials['purple.crane']}
          />
        </group>
        <group
          name="Truck_1002"
          position={[0.202, 0.001, -0.025]}
          rotation={[-Math.PI, 0.001, -Math.PI]}>
          <mesh
            name="Mesh_4001"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_4001.geometry}
            material={materials.gery}
          />
          <mesh
            name="Mesh_4001_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_4001_1.geometry}
            material={materials['purple.truck1']}
          />
        </group>
        <group name="NurbsPath" position={[0.107, 0.001, -0.025]} />
        <group name="windmills" position={[-0.053, 0.027, -0.271]} scale={0.024}
          onClick={() => { console.log("windmills") }}
          onPointerOver={() => { console.log("windmills") }}
        >
          <mesh
            name="Blades_01"
            castShadow
            //receiveShadow
            geometry={nodes.Blades_01.geometry}
            material={materials['purple.wind']}
            position={[0, 0.343, 1.131]}
            scale={42.018}
          />
          <mesh
            name="Blades_02001"
            castShadow
            //receiveShadow
            geometry={nodes.Blades_02001.geometry}
            material={materials['purple.wind']}
            position={[0, 0.343, 0.048]}
            scale={42.018}
          />
          <mesh
            name="Blades_03"
            castShadow
            //receiveShadow
            geometry={nodes.Blades_03.geometry}
            material={materials['purple.wind']}
            position={[0, 0.343, -1.05]}
            scale={42.018}
          />
          <mesh
            name="Hav_Floor1"
            castShadow
            //receiveShadow
            geometry={nodes.Hav_Floor1.geometry}
            material={materials.blue}
            position={[-0.528, -1.074, -0.162]}
            scale={42.018}
          />
          <mesh
            name="Vindmolle_01"
            castShadow
            //receiveShadow
            geometry={nodes.Vindmolle_01.geometry}
            material={materials['purple.wind']}
            position={[0, -0.343, 1.045]}
            scale={42.018}
          />
          <mesh
            name="Vindmolle_04"
            castShadow
            //receiveShadow
            geometry={nodes.Vindmolle_04.geometry}
            material={materials['purple.wind']}
            position={[0, -0.343, -0.039]}
            scale={42.018}
          />
          <mesh
            name="Vindmolle_05"
            castShadow
            //receiveShadow
            geometry={nodes.Vindmolle_05.geometry}
            material={materials['purple.wind']}
            position={[0, -0.343, -1.136]}
            scale={42.018}
          />
        </group>
        <group name="Z_construction" position={[-0.007, 0.013, -0.073]} scale={0.084}>
          <group name="Antenna1" position={[2.157, 0.126, 3.015]} scale={11.861}
            onClick={() => { console.log("Antenna1") }}
            onPointerOver={() => { console.log("Antenna1") }}
          >
            <mesh
              name="Mesh_28"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_28.geometry}
              material={materials.dark_grey}
            />
            <mesh
              name="Mesh_28_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_28_1.geometry}
              material={materials['purple.pillr']}
            />
          </group>
          <group name="Housing_associations_and_condominiums" position={[0.719, -0.066, 1.197]} scale={11.861}
            onClick={() => { console.log("Housing_associations_and_condominiums") }}
            onPointerOver={() => { console.log("Housing_associations_and_condominiums") }}
          >
            <mesh
              name="Mesh_60"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_60.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_60_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_60_1.geometry}
              material={materials['purple.build']}
            />
          </group>
          <group name="Building_2" position={[0.73, -0.12, 1.259]} scale={11.861}>
            <mesh
              name="Mesh_61"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_61.geometry}
              material={materials.green}
            />
            <mesh
              name="Mesh_61_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_61_1.geometry}
              material={materials.gery}
            />
          </group>
          <group name="Car4" position={[0.137, -0.135, 0.819]} scale={11.861}>
            <mesh
              name="Mesh_8"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_8.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_8_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_8_1.geometry}
              material={materials['purple.car']}
            />
          </group>
          <group name="Power_production" position={[3.01, 0.017, -0.747]} scale={11.861}
            onClick={() => { console.log("Power_production") }}
            onPointerOver={() => { console.log("Power_production") }}
          >
            <mesh
              name="Mesh_70"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_70.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_70_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_70_1.geometry}
              material={materials['purple.factory']}
            />
            <mesh
              name="Mesh_70_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_70_2.geometry}
              material={materials.dark_grey}
            />
            <mesh
              name="Mesh_70_3"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_70_3.geometry}
              material={materials.blue}
            />
          </group>
          <mesh
            name="Floor4"
            // castShadow
            receiveShadow
            geometry={nodes.Floor4.geometry}
            material={materials.white}
            position={[0.946, -0.154, 0.238]}
            scale={100}
          />
          <group name="Platform" position={[-1.865, 0.122, -2.63]} scale={11.861}
            onClick={() => { console.log("Platform") }}
            onPointerOver={() => { console.log("Platform") }}
          >
            <mesh
              name="Mesh_83"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_83.geometry}
              material={materials.blue}
            />
            <mesh
              name="Mesh_83_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_83_1.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_83_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_83_2.geometry}
              material={materials.white}
            />
            <mesh
              name="Mesh_83_3"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_83_3.geometry}
              material={materials['purple.H1']}
            />
          </group>
          <group name="Hospital" position={[2.403, -0.103, 1.958]} scale={11.861}
            onClick={() => { console.log("Hospital") }}
            onPointerOver={() => { console.log("Hospital") }}
          >
            <mesh
              name="Mesh_52"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_52.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_52_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_52_1.geometry}
              material={materials['purple.hospital']}
            />
            <mesh
              name="Mesh_52_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_52_2.geometry}
              material={materials.white}
            />
          </group>
          <group name="Houses" position={[1.311, -0.122, 1.358]} scale={11.861}
            onClick={() => { console.log("Houses") }}
            onPointerOver={() => { console.log("Houses") }}
          >
            <mesh
              name="Mesh_6"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_6.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_6_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_6_1.geometry}
              material={materials['purple.house2']}
            />
            <mesh
              name="Mesh_6_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_6_2.geometry}
              material={materials.white}
            />
          </group>
          <mesh
            name="Humans_Man3"
            castShadow
            //receiveShadow
            geometry={nodes.Humans_Man3.geometry}
            material={materials['purple.people']}
            position={[1.15, -0.128, 0.147]}
            scale={11.861}
          />
          <group name="Tunnel" position={[2.911, -0.051, -0.243]} scale={11.861}
            onClick={() => { console.log("Tunnel") }}
            onPointerOver={() => { console.log("Tunnel") }}
          >
            <mesh
              name="Mesh_5"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_5.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_5_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_5_1.geometry}
              material={materials['purple.ccavve2']}
            />
          </group>
          <group name="Municipalities" position={[0.591, 0.004, 0.099]} scale={11.861}
            onClick={() => { console.log("Municipalities") }}
            onPointerOver={() => { console.log("Municipalities") }}
          >
            <mesh
              name="Mesh_42"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_42.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_42_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_42_1.geometry}
              material={materials['purple.watchtower']}
            />
          </group>
          <group name="Road_Railroad23" position={[0.579, -0.156, 0.465]} scale={11.861}>
            <mesh
              name="Mesh_89"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_89.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_89_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_89_1.geometry}
              material={materials.blue}
            />
          </group>
          <mesh
            name="Road_Railroad23001"
            castShadow
            //receiveShadow
            geometry={nodes.Road_Railroad23001.geometry}
            material={materials.gery}
            position={[1.841, -0.088, 1.439]}
            scale={11.861}
          />
          <group name="Sports_arena" position={[0.89, -0.119, -1.331]} scale={11.861}
            onClick={() => { console.log("Sports_arena") }}
            onPointerOver={() => { console.log("Sports_arena") }}
          >
            <mesh
              name="Mesh_51"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_51.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_51_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_51_1.geometry}
              material={materials.green}
            />
            <mesh
              name="Mesh_51_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_51_2.geometry}
              material={materials['purple.stadium']}
            />
            <mesh
              name="Mesh_51_3"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_51_3.geometry}
              material={materials.white}
            />
            <mesh
              name="Mesh_51_4"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_51_4.geometry}
              material={materials.dark_grey}
            />
          </group>
          <group name="Data_center" position={[1.897, -0.086, 0.004]} scale={11.861}
            onClick={() => { console.log("Data_center") }}
            onPointerOver={() => { console.log("Data_center") }}
          >
            <mesh
              name="Mesh_43"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_43.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_43_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_43_1.geometry}
              material={materials['purple.network']}
            />
            <mesh
              name="Mesh_43_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_43_2.geometry}
              material={materials.white}
            />
          </group>
          <group
            name="We_are_Telia"
            position={[0.179, 0.019, 1.186]}
            scale={11.861}
            onClick={() => { console.log("We_are_Telia") }}
            onPointerOver={() => { console.log("We_are_Telia") }}
          >
            <mesh
              name="Mesh_30"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_30.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_30_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_30_1.geometry}
              material={materials['purple.telia']}
            />
          </group>
          <group
            name="Merchandise_trade"
            position={[0.822, -0.097, -0.565]}
            scale={11.861}
            onClick={() => { console.log("Merchandise_trade") }}
            onPointerOver={() => { console.log("Merchandise_trade") }}
          >
            <mesh
              name="Mesh_14"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_14.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_14_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_14_1.geometry}
              material={materials['purple.elactronics']}
            />
            <mesh
              name="Mesh_14_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_14_2.geometry}
              material={materials.white}
            />
          </group>
          <group
            name="Inventory"
            position={[0.687, -0.115, 1.799]}
            scale={11.861}
            onClick={() => { console.log("Inventory") }}
            onPointerOver={() => { console.log("Inventory") }}
          >
            <mesh
              name="Mesh_41"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_41.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_41_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_41_1.geometry}
              material={materials['purple.garage']}
            />
            <mesh
              name="Mesh_41_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_41_2.geometry}
              material={materials.white}
            />
          </group>
          <group
            name="Infrastructure_and_movement_patterns"
            position={[1.141, -0.138, 0.152]}
            scale={11.861}
            onClick={() => { console.log("Infrastructure_and_movement_patterns") }}
            onPointerOver={() => { console.log("Infrastructure_and_movement_patterns") }}
          >
            <mesh
              name="Mesh_90"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_90.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_90_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_90_1.geometry}
              material={materials.green}
            />
            <mesh
              name="Mesh_90_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_90_2.geometry}
              material={materials.lightgreen}
            />
            <mesh
              name="Mesh_90_3"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_90_3.geometry}
              material={materials.white}
            />
            <mesh
              name="Mesh_90_4"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_90_4.geometry}
              material={materials['purple.park']}
            />
            <mesh
              name="Mesh_90_5"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_90_5.geometry}
              material={materials.dark_grey}
            />
            <mesh
              name="Mesh_90_6"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_90_6.geometry}
              material={materials.blue}
            />
          </group>
          <group name="Trees1" position={[0.086, -0.083, 0.872]} scale={11.861}>
            <mesh
              name="Mesh_38"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_38.geometry}
              material={materials.green}
            />
            <mesh
              name="Mesh_38_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_38_1.geometry}
              material={materials.gery}
            />
          </group>
          <group name="Trees1001" position={[0.962, -0.088, 0.013]} scale={11.861}>
            <mesh
              name="Mesh_39"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_39.geometry}
              material={materials.green}
            />
            <mesh
              name="Mesh_39_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_39_1.geometry}
              material={materials.gery}
            />
          </group>
          <mesh
            name="Trees1002"
            castShadow
            //receiveShadow
            geometry={nodes.Trees1002.geometry}
            material={nodes.Trees1002.material}
            position={[0.086, -0.083, 0.872]}
            scale={11.861}
          />
          <mesh
            name="Wings_05"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_05.geometry}
            material={nodes.Wings_05.material}
            position={[0.088, -0.101, 0.861]}
            scale={11.861}
          />
        </group>
        <group name="Man5" position={[0.145, 0.003, -0.013]}>
          <mesh
            name="Mesh_85"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_85.geometry}
            material={materials.dark_grey}
          />
          <mesh
            name="Mesh_85_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_85_1.geometry}
            material={materials.white}
          />
          <mesh
            name="Mesh_85_2"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_85_2.geometry}
            material={materials.skin}
          />
          <mesh
            name="Mesh_85_3"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_85_3.geometry}
            material={materials.hair}
          />
        </group>
        <group name="Park" position={[0.153, 0.004, 0.002]}
          onClick={() => { console.log("Park") }}
          onPointerOver={() => { console.log("Park") }}
        >
          <mesh
            name="Mesh_84"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_84.geometry}
            material={materials.white}
          />
          <mesh
            name="Mesh_84_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_84_1.geometry}
            material={materials.blue}
          />
          <mesh
            name="Mesh_84_2"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_84_2.geometry}
            material={materials.green}
          />
          <mesh
            name="Mesh_84_3"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_84_3.geometry}
            material={materials.gery}
          />
        </group>
        <group name="Woman6" position={[0.14, 0.002, -0.012]}>
          <mesh
            name="Mesh_87"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_87.geometry}
            material={materials.white}
          />
          <mesh
            name="Mesh_87_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_87_1.geometry}
            material={materials.dark_grey}
          />
          <mesh
            name="Mesh_87_2"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_87_2.geometry}
            material={materials.skin}
          />
          <mesh
            name="Mesh_87_3"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_87_3.geometry}
            material={materials.hair}
          />
        </group>
        <group name="larger_companies" position={[-0.004, 0.017, -0.047]} scale={-0.087}
          onClick={() => { console.log("Larger_companies") }}
          onPointerOver={() => { console.log("Larger_companies") }}
        >
          <group
            name="Telia_world_suggestion_new_scenes_0007Building_07"
            position={[-0.112, 0.059, 0.305]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={-0.115}>
            <mesh
              name="Mesh005"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh005.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh005_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh005_1.geometry}
              material={materials.white}
            />
          </group>
          <group
            name="Telia_world_suggestion_new_scenes_0007Building_08"
            position={[0.325, 0.022, -0.077]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={-0.115}>
            <mesh
              name="Mesh006"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh006.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh006_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh006_1.geometry}
              material={materials.white}
            />
          </group>
          <group
            name="Telia_world_suggestion_new_scenes_0007Main_building_Closed1"
            position={[-0.14, -0.055, -0.129]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={-0.115}>
            <mesh
              name="Mesh008"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh008.geometry}
              material={materials['purple.mainbuild']}
            />
            <mesh
              name="Mesh008_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh008_1.geometry}
              material={materials.white}
            />
          </group>
          <group
            name="Telia_world_suggestion_new_scenes_0007Main_building_Open1"
            position={[-0.073, -0.027, -0.1]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={-0.115}>
            <mesh
              name="Mesh009"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh009.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh009_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh009_1.geometry}
              material={materials.green}
            />
            <mesh
              name="Mesh009_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh009_2.geometry}
              material={materials['purple.mainbuild']}
            />
          </group>
        </group>
        <group name="Gravel_roof" position={[-0.217, 0.003, 0.017]} scale={0.034}
          onClick={() => { console.log("Gravel_roof") }}
          onPointerOver={() => { console.log("Gravel_roof") }}
        >
          <group name="Bulldozer_1" position={[0.707, -0.015, -0.291]} scale={38.683}>
            <mesh
              name="Mesh_21"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_21.geometry}
              material={materials['purple.jcb']}
            />
            <mesh
              name="Mesh_21_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_21_1.geometry}
              material={materials.gery}
            />
          </group>
          <mesh
            name="Fence"
            castShadow
            //receiveShadow
            geometry={nodes.Fence.geometry}
            material={materials.gery}
            position={[0.437, 0.036, -0.264]}
            scale={29.543}
          />
          <mesh
            name="Fence3"
            castShadow
            //receiveShadow
            geometry={nodes.Fence3.geometry}
            material={materials.dark_grey}
            position={[-2.766, 0.047, -0.56]}
            scale={29.543}
          />
          <mesh
            name="Grabb"
            castShadow
            //receiveShadow
            geometry={nodes.Grabb.geometry}
            material={materials.gery}
            position={[0.723, -0.035, 0.112]}
            scale={29.543}
          />
          <mesh
            name="Grav"
            castShadow
            //receiveShadow
            geometry={nodes.Grav.geometry}
            material={materials['purple.jcb']}
            position={[0.712, 0.068, -0.084]}
            scale={29.543}
          />
          <group name="Lasteplan_01" position={[0.063, -0.063, 0.47]} scale={29.543}>
            <mesh
              name="Mesh_19"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_19.geometry}
              material={materials['purple.ruck1']}
            />
            <mesh
              name="Mesh_19_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_19_1.geometry}
              material={materials.gery}
            />
          </group>
          <mesh
            name="Lasteplan_02"
            castShadow
            //receiveShadow
            geometry={nodes.Lasteplan_02.geometry}
            material={materials['purple.ruck1']}
            position={[0.062, 0.002, 0.401]}
            scale={29.543}
          />
          <group name="Truck_1001" position={[0.063, -0.04, 0.216]} scale={32.742}>
            <mesh
              name="Mesh_18"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_18.geometry}
              material={materials['purple.ruck1']}
            />
            <mesh
              name="Mesh_18_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_18_1.geometry}
              material={materials.gery}
            />
          </group>
        </group>
        <group name="Cottage" position={[-0.065, 0.031, 0.066]} scale={-0.023}
          onClick={() => { console.log("Cottage") }}
          onPointerOver={() => { console.log("Cottage") }}
        >
          <mesh
            name="Floor001"
            castShadow
            //receiveShadow
            geometry={nodes.Floor001.geometry}
            material={nodes.Floor001.material}
            position={[0.069, 0.247, -0.058]}
            scale={-43.516}
          />
          <group name="Hytte" position={[-0.069, -0.004, 0.058]} scale={-43.516}>
            <mesh
              name="Mesh_53"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_53.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_53_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_53_1.geometry}
              material={materials['purple.house']}
            />
          </group>
          <group name="Hytte_Bottom" position={[-0.229, 0.755, -0.252]} scale={-43.516}>
            <mesh
              name="Mesh_55"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_55.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_55_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_55_1.geometry}
              material={materials['purple.cave']}
            />
          </group>
        </group>
        <group name="Transportation" position={[0.234, 0.002, 0.069]} scale={-0.016}
          onClick={() => { console.log("Transportation") }}
          onPointerOver={() => { console.log("Transportation") }}
        >
          <mesh
            name="Park001"
            castShadow
            //receiveShadow
            geometry={nodes.Park001.geometry}
            material={materials.white}
            position={[0.266, 0.101, -0.051]}
            rotation={[0, 1.571, 0]}
            scale={-43.953}
          />
          <mesh
            name="Road_Railroad23002"
            castShadow
            //receiveShadow
            geometry={nodes.Road_Railroad23002.geometry}
            material={materials.gery}
            position={[0.015, 0.115, -0.038]}
            scale={-62.347}
          />
          <mesh
            name="Small_House1"
            castShadow
            //receiveShadow
            geometry={nodes.Small_House1.geometry}
            material={materials.gery}
            position={[0.146, -0.22, 0.274]}
            scale={-62.347}
          />
          <group name="Truck2" position={[-0.428, 0.004, -0.185]} scale={-62.347}>
            <mesh
              name="Mesh_16"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_16.geometry}
              material={materials['purple.truck']}
            />
            <mesh
              name="Mesh_16_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_16_1.geometry}
              material={materials.gery}
            />
          </group>
        </group>
        <group name="smaller_businesses" position={[0.079, 0.005, -0.005]} scale={-0.017}
          onClick={() => { console.log("Smaller_businesses") }}
          onPointerOver={() => { console.log("Smaller_businesses") }}
        >
          <group
            name="Telia_world_suggestion_new_scenes_0007Small_House_ClosedFront1"
            position={[0.089, -0.077, -0.154]}
            scale={-57.216}>
            <mesh
              name="Mesh_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_1.geometry}
              material={materials['purple.h']}
            />
            <mesh
              name="Mesh_1_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_1_1.geometry}
              material={materials.gery}
            />
          </group>
          <group
            name="Telia_world_suggestion_new_scenes_0007Small_House_Inside2"
            position={[0.048, 0.038, 0.289]}
            scale={-57.216}>
            <mesh
              name="Mesh_0"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_0.geometry}
              material={materials['purple.h']}
            />
            <mesh
              name="Mesh_0_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_0_1.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_0_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_0_2.geometry}
              material={materials.green}
            />
          </group>
          <group
            name="Telia_world_suggestion_new_scenes_0007Small_House_Side1"
            position={[-0.136, 0.039, -0.135]}
            scale={-57.216}>
            <mesh
              name="Mesh_2"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_2.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_2_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_2_1.geometry}
              material={materials.white}
            />
          </group>
        </group>
        <group name="Port_area" position={[-0.105, 0.015, -0.179]} scale={0.03}
          onClick={() => { console.log("Port_area") }}
          onPointerOver={() => { console.log("Port_area") }}
        >
          <group name="Boat_01" position={[0.498, -0.215, -0.352]} scale={33.847}>
            <mesh
              name="Mesh_56"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_56.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_56_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_56_1.geometry}
              material={materials['purple.ship']}
            />
          </group>
          <mesh
            name="Container_treads"
            castShadow
            //receiveShadow
            geometry={nodes.Container_treads.geometry}
            material={materials.purple}
            position={[-0.735, 0.02, -0.3]}
            scale={33.847}
          />
          <group name="Hav_Kran" position={[-0.498, 0.215, 0.352]} scale={33.847}>
            <mesh
              name="Mesh_57"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_57.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_57_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_57_1.geometry}
              material={materials['purple.port']}
            />
          </group>
        </group>
        <group name="contruction_site" position={[-0.195, 0.004, -0.102]} scale={0.027}
          onClick={() => { console.log("Contruction_site") }}
          onPointerOver={() => { console.log("Contruction_site") }}
        >
          <mesh
            name="Fence1"
            castShadow
            //receiveShadow
            geometry={nodes.Fence1.geometry}
            material={materials.gery}
            position={[-0.213, -0.043, 0.165]}
            scale={37.251}
          />
          <mesh
            name="Grabb001"
            castShadow
            //receiveShadow
            geometry={nodes.Grabb001.geometry}
            material={materials.white}
            position={[0.111, -0.083, 0.107]}
            scale={37.251}
          />
          <mesh
            name="Grav001"
            castShadow
            //receiveShadow
            geometry={nodes.Grav001.geometry}
            material={materials['purple.jcb1']}
            position={[0.1, 0.2, -0.041]}
            scale={37.251}
          />
          <group name="Graver2" position={[0.002, -0.073, -0.231]} scale={37.251}>
            <mesh
              name="Mesh_34"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_34.geometry}
              material={materials['purple.jcb1']}
            />
            <mesh
              name="Mesh_34_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_34_1.geometry}
              material={materials.gery}
            />
          </group>
        </group>
        <group name="for_the_employee" position={[0.146, 0.003, -0.008]} scale={0.007}
          onClick={() => { console.log("For_the_employee") }}
          onPointerOver={() => { console.log("For_the_employee") }}
        />
        <group name="Public_transport" position={[0.146, 0.002, -0.032]} scale={-0.006}
          onClick={() => { console.log("Public_transport") }}
          onPointerOver={() => { console.log("Public_transport") }}
        >
          <group name="Bus1" scale={-163.861}>
            <mesh
              name="Mesh_11"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_11.geometry}
              material={materials.gery}
            />
            <mesh
              name="Mesh_11_1"
              castShadow
              //receiveShadow
              geometry={nodes.Mesh_11_1.geometry}
              material={materials.purple_bus_stop}
            />
          </group>
        </group>
        <group
          name="Truck_1003"
          position={[-0.09, 0.001, -0.024]}
          rotation={[-3.136, 1.561, 0]}
          scale={-1}>
          <mesh
            name="Mesh_4004"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_4004.geometry}
            material={materials.gery}
          />
          <mesh
            name="Mesh_4004_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_4004_1.geometry}
            material={materials['purple.truck1']}
          />
        </group>
        <mesh
          name="Drone002"
          castShadow
          //receiveShadow
          geometry={nodes.Drone002.geometry}
          material={materials.purple}
          position={[-0.207, 0.037, -0.287]}
          rotation={[0.013, -1.082, -0.219]}
          scale={0.78}>
          <mesh
            name="Drone5_1003"
            castShadow
            //receiveShadow
            geometry={nodes.Drone5_1003.geometry}
            material={nodes.Drone5_1003.material}
          />
          <mesh
            name="Wings_01010"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_01010.geometry}
            material={materials.gery}
            position={[0.004, 0, 0.005]}
            rotation={[0, -0.598, 0]}
          />
          <mesh
            name="Wings_01011"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_01011.geometry}
            material={materials.gery}
            position={[0.004, 0, -0.004]}
            rotation={[0, -0.598, 0]}
          />
          <mesh
            name="Wings_01012"
            castShadow
            //receiveShadow
            geometry={nodes.Wings_01012.geometry}
            material={materials.gery}
            position={[-0.004, 0, -0.004]}
            rotation={[0, -0.598, 0]}
          />
        </mesh>
        <group
          name="Train_13"
          position={[0.235, 0.004, -0.121]}
          rotation={[-3.095, -0.004, 0]}
          scale={-1}>
          <mesh
            name="Mesh"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh.geometry}
            material={materials['gery.006']}
          />
          <mesh
            name="Mesh_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={materials['purple.006']}
          />
        </group>
        <group
          name="Train_14"
          position={[0.235, 0.005, -0.14]}
          rotation={[-1.524, 0, 0.004]}
          scale={-0.01}>
          <mesh
            name="Mesh019"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh019.geometry}
            material={materials['gery.006']}
          />
          <mesh
            name="Mesh019_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh019_1.geometry}
            material={materials['purple.train.003']}
          />
        </group>
        <group
          name="Train_14001"
          position={[0.235, 0.005, -0.16]}
          rotation={[-1.524, 0, 0.004]}
          scale={-0.01}>
          <mesh
            name="Mesh020"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh020.geometry}
            material={materials['gery.006']}
          />
          <mesh
            name="Mesh020_1"
            castShadow
            //receiveShadow
            geometry={nodes.Mesh020_1.geometry}
            material={materials['purple.train.003']}
          />
        </group>
        <group
          name="NurbsPath001"
          position={[-0.091, 0.001, -0.028]}
          rotation={[Math.PI / 2, 0, 1.571]}
          scale={-0.009}
        />
        <group
          name="NurbsPath002"
          position={[0.236, 0.003, -0.061]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={-0.028}
        />
      </group>
    </group>
  )
})

useGLTF.preload('/model/CONSTRUCTION.glb')
